In [1]:
import numpy as np
import time

a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()

print(c)
print(toc-tic)

249725.17156727583
0.2086620330810547


In [25]:
v = np.array([5,-1,3,2])
print(v)
u = np.exp(v)
print(u)
u = np.maximum(v,0)
print(u)
u = 1/v
print(u)

[ 5 -1  3  2]
[148.4131591    0.36787944  20.08553692   7.3890561 ]
[5 0 3 2]
[ 0.2        -1.          0.33333333  0.5       ]


In [4]:
a = np.random.randn(5,1)
print(a)
print(a.shape)
print(a.T)
print(a.T.shape)

[[ 0.19180667]
 [ 1.93684812]
 [ 1.8862069 ]
 [ 1.03116984]
 [-0.81668472]]
(5, 1)
[[ 0.19180667  1.93684812  1.8862069   1.03116984 -0.81668472]]
(1, 5)


In [11]:
print(np.dot(a.T,a))
print(np.sum( a, axis = 0, keepdims = True ))
assert(a.shape==(5,1))

[[9.07623207]]
[[4.2293468]]
